### ISSUE TITLE
Messages containing NewLine are prematurely ended

### ISSUE THREAD

**Issue by Deantwo** [CaptObvious/HazeronDiscordBot#1]
The bot prematurely ends a message if it contains NewLine chars.

Example:
```html
<font color="#55aaff"><small>15:00 <small>UTC</small> &middot</font><font color="#6666ff"> Shores of Hazeron</font><br><font color="#55aaff">Deantwo</small></font><br><div style="margin-left: 10px;">hey
@CaptObvious#8575
you there?</div>
```
That is a valid message.
But only `[G] Deantwo: hey` appear on Discord.
![image](https://user-images.githubusercontent.com/2676134/58967531-a6929c80-87b4-11e9-92ec-c86b865bde0f.png)

**Comment by CaptObvious** [comment]
Fixed in https://github.com/CaptObvious/HazeronDiscordBot/commit/83715ccaaae6d0d5e2b57d96ebb78f5f712be563
